# Generated by Django 6.0.5 on 2026-05-23 11:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tracking_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('applicant_name', models.CharField(max_length=255)),
                ('applicant_email', models.EmailField(max_length=254)),
                ('company_name', models.CharField(max_length=255)),
                ('application_type', models.CharField(choices=[('Recordation', 'Recordation'), ('Renewal', 'Renewal'), ('Change of Ownership', 'Change of Ownership'), ('Change of Name', 'Change of Name'), ('Discontinuation', 'Discontinuation')], max_length=32)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Under Review', 'Under Review'), ('Need More Information', 'Need More Information'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Draft', max_length=32)),
                ('reviewer_comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
    ]
